/*
Problem 2:
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
        1,2,3,5,8,13,21,34,55,89...
By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
#include <stdio.h>
int main()
{
        int term_pre = 1, term_nex = 2, next = 0, sum = 2; //initialized value of "sum" be '2' because the second term must also added.
        int flag = 1;
        
         while(flag)
         {        
                if (next < 4000000)
                {
                        next = term_pre + term_nex;
                        term_pre = term_nex;
                        term_nex = next;

                        if (next % 2 == 0)
                        {
                                sum += next;
                        }
                }
                else
                {
                        flag = 0;
                }
          }

          printf("%d",sum);
        
        return 0;
}
